### ISSUE TITLE
Inconsistencies between cheatsheet and raylib.h

### ISSUE THREAD

**Issue by baioc** [raysan5/raylib.com#11]
### Issue description

Found some API inconsistencies between the latest [raylib.h][raylib.h] and the [online cheatsheet][cheatsheet], namely:

- Function: `char *LoadText(const char *fileName);`
  Location: Cheatsheet, shaders (rlgl) (should be in module text?).
  Difference: **Seen in the cheatsheet, nowhere to be found in the header file.**

- Function: `Texture GenTextureCubemap(Shader shader, Texture map, int size);`
  Location: raylib.h, near other rlgl functions.
  Difference: **Only found in the header file, along with the next 3 `GenTexture*` functions.**

- Function: `Texture GenTextureIrradiance(Shader shader, Texture cubemap, int size);`
  Location: raylib.h, near other rlgl functions.
  Difference: **Only found in the header file.**

- Function: `Texture GenTexturePrefilter(Shader shader, Texture cubemap, int size);`
  Location: raylib.h, near other rlgl functions.
  Difference: **Only found in the header file.**

- Function: `Texture GenTextureBRDF(Shader shader, int size);`
  Location: raylib.h, near other rlgl functions.
  Difference: **Only found in the header file.**

- Function: `Wave LoadWaveEx(void *data, int sampleCount, int sampleRate, int sampleSize, int channels);`
  Location: Cheatsheet, audio.
  Difference: **Seen only in the cheatsheet.**

- Function: `void SetAudioStreamBufferSizeDefault(int size);`
  Location: raylib.h, the last function declared in that header.
  Difference: **Only found in the header file.**

- Function: `int LoadStorageValue(int position);`
  Location: Both, in the core module under "Persistent storage management".
  Difference: **`position` parameter is an `int` in the cheatsheet, while `unsigned int` in the header.**

- Function: `void SaveStorageValue(int position, int value);`
  Location: Both, in the core module under "Persistent storage management".
  Difference: **`position` parameter is an `int` in the cheatsheet, while `unsigned int` in the header.**

- Function: `unsigned char *LoadFileData(const char *fileName, int *bytesRead);`
  Location: Both, in the core module under "Files management functions".
   Difference: **`bytesRead` parameter is an `int*` in the cheatsheet, while `unsigned int*` in the header.**

- Function: `void SaveFileData(const char *fileName, void *data, int bytesToWrite);`
  Location: Both, in the core module under "Files management functions".
   Difference: **`bytesToWrite` parameter is an `int` in the cheatsheet, while `unsigned int` in the header.**

[raylib.h]: https://github.com/raysan5/raylib/blob/master/src/raylib.h
[cheatsheet]: https://www.raylib.com/cheatsheet/cheatsheet.html

**Comment by raysan5** [comment]
@baioc I'm aware. It has several reasons:

1. Cheatsheet is for `raylib 3.0` while `raylib.h` in github is already WIP for `raylib 3.1`
2. Some functions have been renamed or removed.
3. `GenTexture*()` functions are under review and provably removed.

**Comment by baioc** [comment]
Differences in the last 6 bullet-points also hold for [raylib.h at 3.0.0](https://github.com/raysan5/raylib/blob/3.0.0/src/raylib.h).

**Comment by raysan5** [comment]
@baioc true. Feel free to send a PR with the [cheatsheet files](https://github.com/raysan5/raylib.com/tree/master/cheatsheet) reviewed.

**Comment by baioc** [comment]
@raysan5 regarding `LoadText`, I've now noticed the preprocessor directive defining it as `LoadFileText` in the header.
However, the cheatsheet still has both:

- `char *LoadFileText(const char *fileName);` (under module core) and 
- `char *LoadText(const char *fileName);` (under module **shaders**).

Even if both names were left intentionally in the cheatsheet, it seems to me like they should be at least grouped in the same module.

**Comment by baioc** [comment]
Found another difference: `IsAudioStreamProcessed` is found in the cheatsheet as `IsAudioBufferProcessed`
