### ISSUE TITLE
Broken pages

### ISSUE THREAD

**Issue by SergioFLS** [raysan5/raylib.com#18]
The [Examples](https://www.raylib.com/examples.html) and [Games](https://www.raylib.com/games.html) pages don't seem to load their contents properly.

![Captura de pantalla_2020-12-02_11-45-16](https://user-images.githubusercontent.com/34007063/100888068-98a70000-34ad-11eb-95c0-9c611f3e4446.png)

![Captura de pantalla_2020-12-02_11-46-28](https://user-images.githubusercontent.com/34007063/100888181-becca000-34ad-11eb-8246-28a9fc53766f.png)

Tested both in Firefox and Chromium.

**Comment by raysan5** [comment]
@SergioFLS it works perfectly for me... I need more info to review the issue...

**Comment by jhm-ciberman** [comment]
This is the console output. It seems jQuery is not loading

![image](https://user-images.githubusercontent.com/7988351/101507451-50785980-3955-11eb-8a96-b68c93630b77.png)

**Comment by jhm-ciberman** [comment]
The link to jQuery JS file is broken. The fix is to replace the jquery script tag by the Google CDN: 

```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
```
