### ISSUE TITLE
Default key behaviour should be prevented for examples

### ISSUE THREAD

**Issue by cmann1** [raysan5/raylib.com#20]
Some of the examples use the space or arrow keys which by default will cause the window to scroll making the demo hard to use.

**Comment by raysan5** [comment]
Examples updated! It should work as expected now! :D

**Comment by cmann1** [comment]
I did look into this a bit, but got distracted by other things so I never followed through.
Problem with this is that you can no longer type a space character into text boxes.

So I looked into **text_input_box.js** and found that behind the scenes `GetCharPressed` is mapped javascript's ` keypress` event (supposedly deprecated: https://developer.mozilla.org/en-US/docs/Web/API/Document/keypress_event), and unfortunately calling `preventDefault` in `keydown` also prevents `keypress` from firing.

The only solution I think of is to change this to use keydown and use the `charCode` (also deprecated apparently) or `key` property and filtering out non-printable characters.

I'm not sure if you have control over this though because it looks like it's part of the compile GLFW javascript.

**Comment by raysan5** [comment]
@cmann1 ooh... I see... unfortunately I don't have control over it, emscripten provides [glfw implementation](https://github.com/emscripten-core/emscripten/blob/master/src/library_glfw.js). I've I had more time I'd consider replacing it by my custom implementation...
