### ISSUE TITLE
Grammar mistake in cheatsheet

### ISSUE THREAD

**Issue by GideonSerf** [raysan5/raylib.com#31]
In the cheatsheet for the texture module, there is a note that reads 

> NOTE: This functions do not require GPU access

This should be "_These_ functions do not require GPU access."

![image](https://user-images.githubusercontent.com/11619754/151130885-a0713302-8e7e-49da-ba4a-95d7d77181d0.png)

**Comment by CastimierDev** [comment]
just made a pull request where I fixed the mistake

**Comment by GideonSerf** [comment]
Thank you!
