### ISSUE TITLE
Segmentation fault in LoadModel

### ISSUE THREAD

**Issue by bl-nero** [raysan5/raylib.com#46]
I tried to load [this model](https://www.cgtrader.com/free-3d-models/aircraft/helicopter/cartoon-low-poly-helicopter) and LoadModel consistently segfaults here. First, there's been an assertion triggering that forbids faces with more than 5 sides; when I manually tweaked the model by simplifying the single offending face, it still barfs with a random segfault somewhere higher in the LoadModel function.

Now I would attribute that to my tinkering, but [a different model](https://www.cgtrader.com/free-3d-models/vehicle/other/helicopter-507f7882-f2c3-4660-80b6-d724571cdeec) also results with a segmentation fault, even if it doesn't trigger the assertion.

Unfortunately, it's really hard for me to check what exactly causes it, since when I build a debug version, the segfault doesn't happen, and if I'm trying to just add source information and keep all the optimizations, I find it really hard to attach an lldb in a way that makes it recognize the source code.

I'm working on MacOS Monterey, version 12.5.1, and the error is reproducible both through Rust bindings, as well as the original `models_loading` example. My compiler is `Apple clang version 12.0.0 (clang-1200.0.32.21)`

**Comment by raysan5** [comment]
@bl-nero I'm afraid this repo is for `raylib.com` website, not `raylib` library. For raylib issues, please, open them in raylib repo: https://github.com/raysan5/raylib

About the issue, what model format oare you tryint to load? obj? gltf? In any case, faces need to be triangulated, no quads or >4 sides per face are supported.

**Comment by bl-nero** [comment]
Oops, sorry. Filed https://github.com/raysan5/raylib/issues/2847 instead, including clarification to address your question.
