### ISSUE TITLE
examples page buttons is not working

### ISSUE THREAD

**Issue by ahmedmagdy492** [raysan5/raylib.com#55]
hi guys,
the buttons in this page is not working and not navigating to the appropriate part of the documentation:
![image](https://github.com/raysan5/raylib.com/assets/41495541/c0200cd3-7ce8-4ce7-ba5e-43b342fe4d22)
I've tried it on multiple browsers but it still have the same issue
Edit:
apparently there is an error in the examples.js file that occurs when the page loads:
![image](https://github.com/raysan5/raylib.com/assets/41495541/70b68a77-f581-49fa-ae0c-b44841314d1c)

**Comment by raysan5** [comment]
@ahmedmagdy492 Just reviewed it and I can't reproduce the isssue, could it be related to your internet service provider?

**Comment by ahmedmagdy492** [comment]
It turned out that you are right, yes the issue was caused by my internet service provider, when i tried with a vpn the page just worked properly without any issues.
