### ISSUE TITLE
Add searching by used functions in examples page

### ISSUE THREAD

**Issue by RokasPuzonas** [raysan5/raylib.com#56]
### Issue Description

Add a searchbar to examples page for filtering by raylib functions used in the examples. This is from the [5.0 wishlist](https://github.com/raysan5/raylib/discussions/2952), the "Index functions by usage example." point.

What I already have ([repo](https://github.com/RokasPuzonas/raylib.com/tree/feature-add-function-search)):
![image](https://github.com/raysan5/raylib.com/assets/59289995/2aeea8dd-9507-4d24-8687-2f8364452172)

### Questions/Features

These are some of the problems that I ran into and want some opinions on how it should be solved.

1. Should the search be fuzzy or exact? I though of adding something like a checkbox to switch between fuzzy and exact, but don't know useful it would be. In the current implementation the search is fuzzy so you can't get usage of `DrawRectangle`, because you will get all the other variants of draw rectangle also.
2. Where should the program that indexes all the examples be stored? I saw the generator for cheatsheets is stored within the repository, but should the indexer also be here? Maybe the repository should be transferred to raysan5? The indexer is a CLI program written in C, [here](https://github.com/RokasPuzonas/raylib-example-indexer) is a link to the repository.
3. Should be CLI indexer program should be converted into a rtools style GUI program? Something in the style of "rFXGen"
4. Should a Github Action be used for automatically generating the function usages JSON file? I suspect examples will be added/updated frequently and it would be nice to have some CI/CD for that, so it doesn't go out of sync.
5. Autocompletion of raylib function names? I would imagine the final result of it would look like [this](https://www.w3schools.com/howto/howto_js_autocomplete.asp). Do we want this?

After these questions have been solved, I will create PR for all of it.

**Comment by raysan5** [comment]
@RokasPuzonas Wow! This is quite impressive! About your questions:

1. Probably the fuzzy option is the best one, not only because it considers spelling mistakes but also because many users do not know exactly the function they need or the option available in the library.
2. We need to think carefully about that, the cheatsheet generator is broken (or it didn't worked for me last time I tried) so maintenance is a concern. Also, storing it on the webpage repo has its pros and cons... no idea at the moment. Maybe a `tools` directory in the webpage could be a simple option and so all data is centralized.
3. I don't think so.
4. That would be great but it implies additional work and maintenance.
5. I could be nice but I don't consider it a priority, actually, I see it related to 1.

My questions:

1. What is the overhead this feature adds to the webpage loading/execution?
2. I saw the generated .json is quite big, how long does it take to process a search?

Thank you very much for this amazing addition!

**Comment by RokasPuzonas** [comment]
@raysan5 Heyo!

Huh, I haven't though about spelling mistakes, currently I do a simple ".contains()" to check if user input string matches any part of the functions name. Do you think it would be useful implement a fuzzier search? So things like "Rctangle" would still be considered the same as "Rectangle"?

A simpler alternative to a Github Action, would be wrap up both generating examples and updating the function usage JSON file into a single script, so it's harder to forget doing them both.

Another questions, now that I am looking what functions were indexes, these are not all of them. They are only from "raylib.h", should "raygui.h", "raymath.h", etc. also be included? (The reason for this, because I just used [raylib_parser](https://github.com/raysan5/raylib/tree/master/parser))

Here are my answers to your questions:
1. The execution overhead is low, because the JSON file is already in a convenient format to use. But the loading overhead is 374KB, which isn't the best. In early versions of my implementation, if I entered my text into the searchbar fast enough after reloading the page it would not work, because the file hasn't finished loading.
4. To process a search is quick, I artificially added a 200ms debounce so user would have enough time to enter the full function name. Without the debounce it flickers a lot between having a lot of occurrences and none, because you are still in the middle of typing.

If the size of the JSON file is a concern I have a few solutions:
1. Remove whitespace
2. Don't store occurrence location

Current size of JSON file: 374KB
With whitespace removed: 289KB
With whitespace and locations removed: 96KB

Why locations were stored is that at first, I imagined that it would be cool to highlight the places were that function was found. Like using find (Ctrl+F) function in an IDE. But implementing this I think could be annoying, because the pop up that shows up when you click on an example is in an iframe. After a quick search I didn't find a straightforward way to pass data into a iframe, it would need to be done using events.

**Comment by raysan5** [comment]
@RokasPuzonas About the JSON size concerns and solution, probably removing whitespaces and locations is the best option for most users but it code (and bigger file) could be kept as an option for the future.
