### ISSUE TITLE
Link Error of License in Readme

### ISSUE THREAD

**Issue by pauladam94** [raysan5/raylib.com#76]
At the end of the readme there is a link to see the LICENSE :
I am using firefox and seeing this file on github.
The link redirected me to this page :
```txt
https://github.com/raysan5/raylib.com/blob/master/LICENSE.md
```
This is an 404 error.

There should be this link instead : 
```txt
https://github.com/raysan5/raylib.com/blob/master/LICENSE
```

There is ".md" is the link which should not be here.

**Comment by raysan5** [comment]
FIXED!
